name: DICOM ➜ JPEG ➜ IIIF Manifest

# ❶ .dcm 파일이 push 될 때마다, 또는 수동 트리거(workflow_dispatch)로 실행
on:
  push:
    paths:
      - '**.dcm'
  workflow_dispatch:      # GitHub UI에서 수동 실행도 허용

jobs:
  build-iiif:
    runs-on: ubuntu-latest

    # auto-commit 액션이 main 브랜치에 쓰기권한을 쓰도록 허용
    permissions:
      contents: write

    steps:
    # 1) 저장소 체크아웃
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0        # 전체 히스토리 보존(자동 커밋 시 충돌 최소화)

    # 2) Python 3.12 설치
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # 3) 필요한 파이썬 패키지 설치
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pydicom pillow numpy biiif

    # 4) DICOM → JPEG 변환 (scripts/dicom2jpg.py 작성 필요)
    - name: Convert DICOM to JPEG
      run: |
        python scripts/dicom2jpg.py

    # 5) IIIF Manifest 재생성 (scripts/build_manifest.py 작성 필요)
    - name: Build IIIF Manifest
      run: |
        python scripts/build_manifest.py \
          --images_dir images \
          --output manifest.json \
          --base_url "https://song-jung-il.github.io/Public_image"

    # 6) 변경 파일 자동 커밋 & 푸시
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "auto: refresh JPEG & manifest"
        branch: main
